src/Entity/Opera.php
<?php

namespace App\Entity;

use App\Repository\OperaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass=OperaRepository::class)
 */
class Opera
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Patient::class, inversedBy="operas")
     * @ORM\JoinColumn(nullable=false)
     */
    private $patient;

    /**
     * @ORM\ManyToOne(targetEntity=Treatment::class, inversedBy="operas")
     * @ORM\JoinColumn(nullable=false)
     */
    private $treatment;

    /**
     * @ORM\Column(type="datetime")
     * @Gedmo\Timestampable(on="create")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $made_at;

    /**
     * @ORM\ManyToOne(targetEntity=Place::class, inversedBy="operas")
     */
    private $place;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="operas")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="float", options={"default" : 0.0})
     */
    private $value;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $notes;

    /**
     * @ORM\OneToMany(targetEntity=Charge::class, mappedBy="opera")
     */
    private $charges;

    /**
     * @ORM\Column(type="string", length=63, nullable=true)
     */
    private $operateur;

    /**
     * @ORM\Column(type="string", length=63, nullable=true)
     */
    private $assistent;

    /**
     * @ORM\Column(type="string", length=63, nullable=true)
     */
    private $omloop;

    /**
     * @ORM\Column(type="string", length=63, nullable=true)
     */
    private $anesthesie;

    /**
     * @ORM\Column(type="string", length=63, nullable=true)
     */
    private $anesthesie_md;

    /**
     * @ORM\Column(type="boolean", options={"default" : false})
     */
    private $re_ok;

    /**
     * @ORM\Column(type="boolean", options={"default" : false})
     */
    private $complica;

    public function __construct()
    {
        $this->charges = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPatient(): ?Patient
    {
        return $this->patient;
    }

    public function setPatient(?Patient $patient): self
    {
        $this->patient = $patient;

        return $this;
    }

    public function getTreatment(): ?Treatment
    {
        return $this->treatment;
    }

    public function setTreatment(?Treatment $treatment): self
    {
        $this->treatment = $treatment;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getMadeAt(): ?\DateTimeInterface
    {
        return $this->made_at;
    }

    public function setMadeAt(?\DateTimeInterface $made_at): self
    {
        $this->made_at = $made_at;

        return $this;
    }

    public function getPlace(): ?Place
    {
        return $this->place;
    }

    public function setPlace(?Place $place): self
    {
        $this->place = $place;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getValue(): ?float
    {
        return $this->value;
    }

    public function setValue(float $value): self
    {
        $this->value = $value;

        return $this;
    }

    public function getNotes(): ?string
    {
        return $this->notes;
    }

    public function setNotes(?string $notes): self
    {
        $this->notes = $notes;

        return $this;
    }

    /**
     * @return Collection|Charge[]
     */
    public function getCharges(): Collection
    {
        return $this->charges;
    }

    public function addCharge(Charge $charge): self
    {
        if (!$this->charges->contains($charge)) {
            $this->charges[] = $charge;
            $charge->setOpera($this);
        }

        return $this;
    }

    public function removeCharge(Charge $charge): self
    {
        if ($this->charges->contains($charge)) {
            $this->charges->removeElement($charge);
            // set the owning side to null (unless already changed)
            if ($charge->getOpera() === $this) {
                $charge->setOpera(null);
            }
        }

        return $this;
    }

    public function getOperateur(): ?string
    {
        return $this->operateur;
    }

    public function setOperateur(?string $operateur): self
    {
        $this->operateur = $operateur;

        return $this;
    }

    public function getAssistent(): ?string
    {
        return $this->assistent;
    }

    public function setAssistent(?string $assistent): self
    {
        $this->assistent = $assistent;

        return $this;
    }

    public function getOmloop(): ?string
    {
        return $this->omloop;
    }

    public function setOmloop(?string $omloop): self
    {
        $this->omloop = $omloop;

        return $this;
    }

    public function getAnesthesie(): ?string
    {
        return $this->anesthesie;
    }

    public function setAnesthesie(?string $anesthesie): self
    {
        $this->anesthesie = $anesthesie;

        return $this;
    }

    public function getAnesthesieMd(): ?string
    {
        return $this->anesthesie_md;
    }

    public function setAnesthesieMd(?string $anesthesie_md): self
    {
        $this->anesthesie_md = $anesthesie_md;

        return $this;
    }

    public function getReOk(): ?bool
    {
        return $this->re_ok;
    }

    public function setReOk(bool $re_ok): self
    {
        $this->re_ok = $re_ok;

        return $this;
    }

    public function getComplica(): ?bool
    {
        return $this->complica;
    }

    public function setComplica(bool $complica): self
    {
        $this->complica = $complica;

        return $this;
    }
}

src/Controller/PatientController.php
<?php

namespace App\Controller;

use SuperSaaS\Client;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Doctrine\ORM\EntityManagerInterface;


use App\Entity\Patient;

use App\Entity\Consult;
use App\Entity\Medicat;
use App\Entity\Historia;
use App\Entity\Opera;

use App\Entity\DocPatient;
use App\Entity\DocImgPatient;


use App\Form\PatientType;
use App\Form\ConsultType;

use App\Form\DocPatientType;
use App\Form\DocImgPatientType;

use App\Service\UploaderHelper;
use Knp\Component\Pager\PaginatorInterface;

use App\Repository\PatientRepository;

/**
 * Controller used to manage current user.
 *
 * @Security("is_granted('ROLE_USER')")
 *
 */
class PatientController extends AbstractController
{


    /**
     * @Route("/{slug}/patient/search", methods={"GET"}, name="patient_search")
     * @param Request $request
     * @param PatientRepository $patients
     * @param $slug
     * @return Response
     * @throws \Exception
     */
    public function searchPat(Request $request, PatientRepository $patients, $slug): Response
    {
        $center = $this->getUser()->getCenter();

        $this->denyAccessUnlessGranted('CENTER_VIEW', $center);
        ///////////////////////////////////////////////////////
        if (!$request->isXmlHttpRequest()) {
            return $this->render('patient/search.html.twig',[
                'center' => $center,
            ]);
        }
        $centerId = $center->getId();

        $query = $request->query->get('q', '');

        //  $request->getSession()->set('query', $query); Recordamos la búsqueda anterior ?

        $limit = $request->query->get('l', 10);
        $foundPatients = $patients->findBySearchQuery($query, $limit, $centerId);

        $results = [];

        foreach ($foundPatients as $patient) {

            if($patient->getSex()) {
                $sex =' <i class="fa fa-venus text-danger"></i> ';
            } else {
                $sex =' <i class="fa fa-mars text-info"></i> ';
            };
 
            $dob = new \DateTime($patient->getDateOfBirth()->format('Y-m-d'));
            $today = new \DateTime('today');

            $age = $today->diff($dob)->y;
         
            $results[] = [

                'url' => $this->generateUrl('patient_show', ['id' => $patient->getId(), 'slug' => $center->getSlug()]),

                'id' => htmlspecialchars($patient->getId(), ENT_COMPAT | ENT_HTML5),
                'firstname' => htmlspecialchars($patient->getFirstname(), ENT_COMPAT | ENT_HTML5),
                'lastname' => htmlspecialchars($patient->getLastname(), ENT_COMPAT | ENT_HTML5),
                'birthdate' => $patient->getDateOfBirth()->format('d/m/Y'),
                'sex' => $sex,
                'age' => $age,
            ];
        }
        return $this->json($results);        

    }


    /**
     * @Route("/{slug}/patients", methods={"GET"}, name="patient_index")
     * @param Request $request
     * @param PaginatorInterface $paginator
     * @return Response
     */
    public function indexPat(Request $request, PaginatorInterface $paginator)
    {

        //$lastIdPat = $this->getDoctrine()->getRepository(Patient::class)->lastInsertedId();
        //$lastIdPat = $lastIdPat['lastIdPat'];

        //var_dump($lastIdPat);die;

        $group = '';

        $entity = $request->get('entity');
        $entity_id = $request->get('id');

        $center = $this->getUser()->getCenter();

        $em = $this->getDoctrine()->getManager();

        

        $queryBuilder = $em->createQueryBuilder($center->getId())
            ->select('p', 's', 'i') 
            ->from('App\Entity\Patient', 'p')
            ->innerJoin('p.user','u')
            ->innerJoin('u.center','c')
            ->leftJoin('p.source', 's')
            ->leftjoin('p.insurance', 'i')
            
            ->orderBy('p.id', 'DESC');
            
            // ->leftjoin('p.place', 'pl')

            // ->setParameter('last', $lastIdPat);
            // ->andWhere('p.id + 100 > :last')

        if($center->getId()){
            $queryBuilder
                ->andWhere('c.id = :val')
                ->setParameter('val', $center->getId());
        };

        if($entity && $entity_id){
            switch($entity){
            case 'ins':
                $queryBuilder
                    ->andWhere('p.insurance = :insuranceId')
                    ->setParameter('insuranceId', $entity_id);
            break;    
            case 'source':
                $queryBuilder
                    ->andWhere('p.source = :sourceId')
                    ->setParameter('sourceId', $entity_id);
            break;    
            case 'place':
                $queryBuilder
                    ->andWhere('p.place = :placeId')
                    ->setParameter('placeId', $entity_id);
            break;    

            }

        };

        #$queryBuilder->setMaxResults('100');
            
       
        $pagination = $paginator->paginate(
            $queryBuilder, /* query NOT result */
            $request->query->getInt('page', 1)/*page number*/,
            10/*limit per page*/
        );

     

        return $this->render('patient/index.html.twig', [
             
            'group' => $group,
            'center' => $center,
            'pagination' => $pagination, 
            'order' => 'íd',
        ]);

    }


    /**
     * @Route("/{slug}/new/patient", methods={"GET", "POST"}, name="patient_new")
     *
     * NUEVO paciente (del usuario)
     * @param Request $request
     * @param $slug
     * @return Response
     */
    public function newPat(Request $request, $slug): Response
    {

        $user = $this->getUser();
        $center = $user->getCenter();

        $this->denyAccessUnlessGranted('CENTER_EDIT', $center);

        // Todos pueden insertar pacientes !?

        $patient = new Patient();
        $patient->setUser($user);

        $form = $this->createForm(PatientType::class, $patient);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $em = $this->getDoctrine()->getManager();
            $em->persist($patient);
            $em->flush();

            $this->addFlash('info', 'record.updated_successfully');

            return $this->redirectToRoute('patient_show', ['slug' => $slug, 'id' => $patient->getId()]);
        }

        return $this->render('/patient/new.html.twig', [
             
            'patient' => $patient,
            'form' => $form->createView(),
            
        ]);

    }

    /**
     * @Route("{slug}/patient/{id}/show", methods={"GET", "POST"}, name="patient_show")
     *
     * MOSTRAR el paciente id
     * @param Request $request
     * @param $slug
     * @param Patient $patient
     * @param EntityManagerInterface $em
     * @param UploaderHelper $uploaderHelper
     * @return Response
     * @throws \Exception
     */
    public function showPat(Request $request, $slug, Patient $patient, EntityManagerInterface $em, UploaderHelper $uploaderHelper): Response
    {
        $this->denyAccessUnlessGranted('PATIENT_VIEW', $patient);

        $patId = $patient->getId();
        
        $center = $this->getUser()->getCenter();

        $agendas = null;
        $ac_name = null;
        $api_key = null;
        $checksum = null;
        $arguments = null;

        if($center->getSsaasAccountName() && $center->getSsaasApiKey()) {

            $ac_name = $center->getSsaasAccountName();
            $api_key = $center->getSsaasApiKey();

            $client = new Client();

            $client->api_key = $api_key;
            $client->account_name = $ac_name;
            try{
                $agendas = $client->schedules->getList();
            } catch (\Exception $e) {

            }


            $checksum = md5($ac_name . $api_key . $this->getUser()->getEmail());

            $SS_1_r = $patient->getId() . ' - ' . ' ' . $patient->getFirstname() . ' ' . $patient->getLastname();

            if($patient->getSex() == 1){
                $SS_2_r = "(V) ";
            } else {
                if($patient->getSex() == 0){
                    $SS_2_r = "(M) ";
                } else {
                    $SS_2_r = "(?) ";
                }
            }

            $SS_2_r .= $patient->getDateOfBirth()->format('d/m/Y');
            $SS_2_r .= ' (' . $patient->getCel() . ' - ' . $patient->getTel() . ')';
            $SS_2_r .= ' BSN ' . $patient->getCode1();
            if (! is_null($patient->getInsurance()) ){
                $SS_2_r .=  ' > ' . $patient->getInsurance()->getName();
            };



            $arguments = "?res[field_1_r]=" . $SS_1_r . "&res[field_2_r]=" . $SS_2_r;

        }

                
        $repository = $em->getRepository(Consult::class);
        $consults = $repository->findBy(['patient' => $patId], ['created_at' => 'DESC']);

        $repository = $em->getRepository(Historia::class);
        $historias = $repository->findBy(['patient' => $patId], ['date' => 'DESC']);

        $repository = $em->getRepository(Medicat::class);
        $medicats = $repository->findBy(['patient' => $patId], ['created_at' => 'DESC']);

        $repository = $em->getRepository(Opera::class);
        $operas = $repository->findBy(['patient' => $patId], ['created_at' => 'DESC']);

        ///////////////////////////////////////////////
        # $debts = $repository->findNotPaidOpera($patId); 
        // var_dump($debts);die;

        $repository = $em->getRepository(docImgPatient::class);
        $imgs = $repository->findBy(['patient' => $patId], ['updated_at' => 'DESC']);
        $repository = $em->getRepository(docPatient::class);
        $docs = $repository->findBy(['patient' => $patId], ['updated_at' => 'DESC']);

templates/patient/opera/edit.html.twig
{% extends 'base.html.twig' %}

{% block body_id 'opera_edit' %}

{% block title %}{{ opera.id }}{% endblock %}

{% block body %}

    {{ form_start(operaForm, {'attr': {'novalidate': 'novalidate'}}) }}

        <div class="container">

            <div class="row justify-content-between">

                <div class="col-sm-auto">

                    <h4>
                        
                        {{opera.treatment.name}} | <i class="fa fa-user-injured"></i> {{ opera.patient.firstname }} {{ opera.patient.lastname }} &nbsp;
                        {% if opera.patient.sex %}
                            <i class="fa fa-venus text-danger"></i>
                        {% else %}
                            <i class="fa fa-mars text-info"></i>
                        {% endif %}
                        {{ opera.patient.dateOfBirth | age }}

                    </h4>
            
                </div>

                <div class="col"></div>

            </div>

            {{ form_errors(operaForm) }}

            <div class="form-row">

                <div class="form-group col-3">
                    {{ form_row(operaForm.user, {
                        label: 'Dr.',
                    }) }}
                </div>

                <div class="form-group col-6">
                    {{ form_row(operaForm.treatment, {
                        
                    }) }}

                    {# disabled: true #}

                </div>


            </div>

            <div class="form-row">

                <div class="form-group has-feedback col-3">
                    {{ form_row(operaForm.made_at, {
                        label: 'Programada para',
                        attr: {
                            class: 'js-datepicker'
                        }
                    }) }}
                </div>

                <div class="form-group col-6">
                    {{ form_row(operaForm.place) }}
                </div>



            </div>

            <div class="form-row">


            </div>


        </div>

        <div class="container">

            <div class="card border-success mb-3">

                <div class="card-header">

                    <div class="row justify-content-between">


                        <div class="col-3 text-right">
                            <button class="btn btn-outline-primary btn-block" type="button" data-toggle="collapse" data-target="#collapseNewCon2" aria-expanded="false" aria-controls="collapseExample">
                                {# Button with data-target #}
                                <i class="fa fa-clipboard" aria-hidden="true"></i> Detailed Info
                            </button>
                        </div>

                    </div>

                </div>

                <div class="card card-body collapse" id="collapseNewCon2">
                    <div class="form-row">
                        <div class="form-group col-3">
                            {{ form_row(operaForm.operateur, {
                            }) }}
                        </div>
                        <div class="form-group col-3">
                            {{ form_row(operaForm.assistent, {
                            }) }}
                        </div>
                        <div class="form-group col-3">
                            {{ form_row(operaForm.omloop, {
                            }) }}
                        </div>

                        <div class="form-group col-3 text-right text-danger">
                            {{ form_row(operaForm.re_ok, {
                            }) }}
                            {{ form_row(operaForm.complica, {
                            }) }}
                        </div>

                    </div>
                    <div class="form-row">
                        <div class="form-group col-3">
                            {{ form_row(operaForm.anesthesie, {
                            }) }}
                        </div>
                        <div class="form-group col-3">
                            {{ form_row(operaForm.anesthesie_md, {
                            }) }}
                        </div>

                    </div>

                </div>

            </div>

        </div>

        <div class="container">

        <div class="card border-success mb-3">

            <div class="card-header">

                <div class="row justify-content-between">

                    <div class="form-group col-3">
                        <a href="{{ path('patient_show', {slug:app.user.center.slug, id:opera.patient.id, tab:'#nav-3'}) }}" class="btn btn-success btn-block">
                            <i class="fa fa-arrow-left"></i> {{ 'label.treatments'|trans }}
                        </a>
                    </div>

                    <div class="form-group col-3">
                        <button type="submit" class="btn btn-primary btn-block">
                            <i class="fa fa-save" aria-hidden="true"></i> {{ 'action.save'|trans }}
                        </button>
                    </div>

                    <div class="col-3 text-right">
                        <button class="btn btn-info btn-block" type="button" data-toggle="collapse" data-target="#collapseNewCon" aria-expanded="false" aria-controls="collapseExample">
                            {# Button with data-target #}
                            <i class="fa fa-clipboard" aria-hidden="true"></i> ECO Info
                        </button>
                    </div>

                </div>

            </div>

            <div class="card card-body collapse" id="collapseNewCon">
                <div class="form-row">
                    {{ form_row(operaForm.value) }}
                </div>
            </div>

        </div>

    </div>


        <div class="form-row">
        </div>

    </div>

    {{ form_end(operaForm) }}

{% endblock %}

templates/patient/opera/index_place.html.twig
{% extends 'base_ad.html.twig' %}

{% block main %}

<div class="container">

    <div class="row justify-content-between">

        <div class="col-auto">
            <h4>
                <a href="{{ path('center_cpanel', {slug:slug}) }}">
                    <i class="fa fa-arrow-left" aria-hidden="true"></i>{{ app.user.center.name }}
                </a> 
                | <a href="{{ path('places_index', {slug:app.user.center.slug} ) }}">
                <i class="fa fa-arrow-left" aria-hidden="true"></i>{{ 'label.places'|trans }}</a>  <i class="fa fa-hospital-alt"></i> 
                {{ place.name}}
            </h4>
        </div>        

        <div class="col text-right">
            <a href="{{ path('source_new', {slug:slug}) }}" class="btn btn-primary">
                <i class="fa fa-edit" aria-hidden="true"></i> {{ 'action.new'|trans }}
            </a>
        </div>        

    </div>

</div>
        
    <br>

    <table class="table table-striped table-hover table-responsive">

        <thead>

            <tr>
            
                <th>{{ 'label.date'|trans }}</th>
                <th>{{ 'label.treatment'|trans }}</th>
                <th>{{ 'label.patient'|trans }}</th>
            </tr>

        </thead>

        <tbody>

        {% for opera in operas %}

        <tr>
            
            

            <td>{{ opera.madeAt|date('d-m-y') }}</td>
            <td>{{ opera.treatment.name }}</td>
            
            <td class="text-left">
                {% if opera.patient.dateOfBirth != null %} {{ opera.patient.dateOfBirth | age }} {% endif %}
            {% if opera.patient.sex == 1 %}
                <i class="fa fa-venus text-danger"></i>
            {% else %}
                <i class="fa fa-mars text-info"></i>
            {% endif %}     
<a href="{{ path('patient_show', {slug:app.user.center.slug, id:opera.patient.id} ) }}">{{ opera.patient.firstname }} {{ opera.patient.lastname }}</a> </td>
            
            
        </tr>
        {% endfor %}

    </tbody>

    </table>

{% endblock %}

templates/patient/opera/index_treatment.html.twig
{% extends 'base_ad.html.twig' %}

{% block main %}

    <div class="container">

        <div class="row justify-content-between">

            <div class="col-auto">
                <h4>
                    <a href="{{ path('center_cpanel', {slug:slug}) }}">
                        <i class="fa fa-arrow-left" aria-hidden="true"></i>{{ app.user.center.name }}
                    </a> 
                    | <a href="{{ path('treats_index', {slug:app.user.center.slug, id:treatment.type.id} ) }}">
                    <i class="fa fa-arrow-left" aria-hidden="true"></i>{{ 'label.treatments'|trans }}</a>  <i class="fa fa-file-medical-alt"></i>
                    {{ treatment.name}}
                </h4>
            </div>        

            <div class="col text-right">
                <a href="{{ path('source_new', {slug:slug}) }}" class="btn btn-primary">
                    <i class="fa fa-edit" aria-hidden="true"></i> {{ 'action.new'|trans }}
                </a>
            </div>        

        </div>

    </div>
        
    <br>

    <table class="table table-striped table-hover table-responsive">

        <thead>

            <tr>
            
                <th>{{ 'label.date'|trans }}</th>
                <th>{{ 'label.treatment'|trans }}</th>
                <th>{{ 'label.patient'|trans }}</th>
                <th>{{ 'label.place'|trans }}</th>
            </tr>

        </thead>

        <tbody>

        {% for opera in operas %}

        <tr>
            
            

            <td>{{ opera.madeAt|date('d-m-y') }}</td>
            <td>{{ opera.treatment.name }}</td>
            
            <td class="text-left">
                {% if opera.patient.dateOfBirth != null %} {{ opera.patient.dateOfBirth | age }} {% endif %}
            {% if opera.patient.sex == 1 %}
                <i class="fa fa-venus text-danger"></i>
            {% else %}
                <i class="fa fa-mars text-info"></i>
            {% endif %}     
            <a href="{{ path('patient_show', {slug:app.user.center.slug, id:opera.patient.id} ) }}">{{ opera.patient.firstname }} {{ opera.patient.lastname }}</a> </td>
            <td>{% if opera.place.name is defined %}{{ opera.place.name }}{% endif %}</td>
            
        </tr>
        {% endfor %}

    </tbody>

    </table>


{% endblock %}