src/Entity/Center.php
<?php

namespace App\Entity;

use App\Repository\CenterRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass=CenterRepository::class)
 */
class Center
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $contact_person;

    /**
     * @ORM\Column(type="string", length=63, nullable=true)
     */
    private $tel;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=127, nullable=true)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=31, nullable=true)
     */
    private $postcode;

    /**
     * @ORM\Column(type="string", length=63, nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="boolean")
     */
    private $enabled;

    /**
     * @ORM\OneToMany(targetEntity=User::class, mappedBy="center")
     */
    private $users;

    /**
     * @ORM\Column(type="datetime")
     * @Gedmo\Timestampable(on="create")
     */
    private $created_at;

    /**
     * @ORM\OneToOne(targetEntity=User::class, cascade={"persist", "remove"})
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255)
     * @Gedmo\Slug(fields={"name"}) 
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=127, nullable=true)
     */
    private $ssaas_account_name;

    /**
     * @ORM\Column(type="string", length=127, nullable=true)
     */
    private $ssaas_api_key;

    /**
     * @ORM\OneToMany(targetEntity=DocCenterGroup::class, mappedBy="center")
     */
    private $docCenterGroups;

    /**
     * @ORM\OneToMany(targetEntity=Insurance::class, mappedBy="center")
     */
    private $insurances;

    /**
     * @ORM\OneToMany(targetEntity=Source::class, mappedBy="center")
     */
    private $sources;

    /**
     * @ORM\OneToMany(targetEntity=Type::class, mappedBy="center", orphanRemoval=true)
     */
    private $types;

    /**
     * @ORM\OneToMany(targetEntity=Place::class, mappedBy="center", orphanRemoval=true)
     */
    private $places;

    /**
     * @ORM\OneToMany(targetEntity=ReportType::class, mappedBy="center")
     */
    private $reportTypes;

    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->docCenterGroups = new ArrayCollection();
        $this->insurances = new ArrayCollection();
        $this->sources = new ArrayCollection();
        $this->types = new ArrayCollection();
        $this->places = new ArrayCollection();
        $this->reportTypes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getContactPerson(): ?string
    {
        return $this->contact_person;
    }

    public function setContactPerson(?string $contact_person): self
    {
        $this->contact_person = $contact_person;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(?string $tel): self
    {
        $this->tel = $tel;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostcode(): ?string
    {
        return $this->postcode;
    }

    public function setPostcode(?string $postcode): self
    {
        $this->postcode = $postcode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getEnabled(): ?bool
    {
        return $this->enabled;
    }

    public function setEnabled(bool $enabled): self
    {
        $this->enabled = $enabled;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->setCenter($this);
        }

        return $this;
    }

    // Ojo !
    public function removeUser(User $user): self
    {
        if ($this->users->contains($user)) {
            $this->users->removeElement($user);
            // set the owning side to null (unless already changed)
            if ($user->getCenter() === $this) {
                $user->setCenter(null);
            }
        }

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }




    public function getPatientsNo()
    {
        $patientsNo = 0;
        foreach ($this->users as $user) {
            $patientsNo += $user->getPatients()->count();
        }
        return $patientsNo;
    }

    public function getSsaasAccountName(): ?string
    {
        return $this->ssaas_account_name;
    }

    public function setSsaasAccountName(?string $ssaas_account_name): self
    {
        $this->ssaas_account_name = $ssaas_account_name;

        return $this;
    }

    public function getSsaasApiKey(): ?string
    {
        return $this->ssaas_api_key;
    }

    public function setSsaasApiKey(?string $ssaas_api_key): self
    {
        $this->ssaas_api_key = $ssaas_api_key;

        return $this;
    }

    /**
     * @return Collection|DocCenterGroup[]
     */
    public function getDocCenterGroups(): Collection
    {
        return $this->docCenterGroups;
    }

    public function addDocCenterGroup(DocCenterGroup $docCenterGroup): self
    {
        if (!$this->docCenterGroups->contains($docCenterGroup)) {
            $this->docCenterGroups[] = $docCenterGroup;
            $docCenterGroup->setCenter($this);
        }

        return $this;
    }

    public function removeDocCenterGroup(DocCenterGroup $docCenterGroup): self
    {
        if ($this->docCenterGroups->contains($docCenterGroup)) {
            $this->docCenterGroups->removeElement($docCenterGroup);
            // set the owning side to null (unless already changed)
            if ($docCenterGroup->getCenter() === $this) {
                $docCenterGroup->setCenter(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Insurance[]
     */
    public function getInsurances(): Collection
    {
        return $this->insurances;
    }

    public function addInsurance(Insurance $insurance): self
    {
        if (!$this->insurances->contains($insurance)) {
            $this->insurances[] = $insurance;
            $insurance->setCenter($this);
        }

        return $this;
    }

    public function removeInsurance(Insurance $insurance): self
    {
        if ($this->insurances->contains($insurance)) {
            $this->insurances->removeElement($insurance);
            // set the owning side to null (unless already changed)
            if ($insurance->getCenter() === $this) {
                $insurance->setCenter(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Source[]
     */
    public function getSources(): Collection
    {
        return $this->sources;
    }

    public function addSource(Source $source): self
    {
        if (!$this->sources->contains($source)) {
            $this->sources[] = $source;
            $source->setCenter($this);
        }

        return $this;
    }

    public function removeSource(Source $source): self
    {
        if ($this->sources->contains($source)) {
            $this->sources->removeElement($source);
            // set the owning side to null (unless already changed)
            if ($source->getCenter() === $this) {
                $source->setCenter(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Type[]
     */
    public function getTypes(): Collection
    {
        return $this->types;
    }

    public function addType(Type $type): self
    {
        if (!$this->types->contains($type)) {
            $this->types[] = $type;
            $type->setCenter($this);
        }

        return $this;
    }

    public function removeType(Type $type): self
    {
        if ($this->types->contains($type)) {
            $this->types->removeElement($type);
            // set the owning side to null (unless already changed)
            if ($type->getCenter() === $this) {
                $type->setCenter(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Place[]
     */

src/Form/CenterType.php
<?php

namespace App\Form;

use App\Entity\Center;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;

use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

use Symfony\Component\Security\Core\Security;

use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;


class CenterType extends AbstractType
{

    private $isAdmin;
    private $isSuper;
    private $userRequestsCenterId;

    public function __construct(Security $security)
    {
        $this->isSuper = false;
        $this->userRequestsCenterId = $security->getUser()->getCenter()->getId();

        $this->isSuper = false;
        if (in_array('ROLE_SUPER_ADMIN', $security->getUser()->getRoles())) {
            $this->isSuper = true;
            $this->isAdmin = true;
        }

        $this->isAdmin = false;
        if (in_array('ROLE_ADMIN', $security->getUser()->getRoles())) {
            $this->isAdmin = true;
        }

    }

   

    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        $builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) {

            $center = $event->getData();
            $form = $event->getForm();
            
            if( $this->isSuper && $center->getId() <> $this->userRequestsCenterId && $center->getId() ){

                // 

                // Solo para el superusuario que no edita su mismo centro y no para centros nuevos

                $form->add('enabled', CheckboxType::class, [
                    'label' => 'label.enabled',
                    'required' => false,
                ]);

            }


            if ($this->isSuper && $center->getId()) // Solo los SUPER entran y solo para centros ya creados !!!!
            {
                $form->add('ssaas_account_name', TextType::class, [
                    'label' => 'Ssaas Account name',
                    'required' => false,
                ]);
                $form->add('ssaas_api_key', TextType::class, [
                    'label' => 'Ssaas API key',
                    'required' => false,
                ]);

            }

            $form->add('name', TextType::class, [
                'label' => 'label.name',
            ])

            ->add('contact_person', TextType::class, [
                'label' => 'label.contact_person',
                'required' => false,
            ])

            ->add('tel', TelType::class, [
                'label' => 'label.tel',
                'required' => false,
            ])

            ->add('email', EmailType::class, [
                'label' => 'label.email',
            ])

            ->add('address', TextType::class, [
                'label' => 'label.address',
                'required' => false,
            ])

            ->add('postcode', TextType::class, [
                'label' => 'label.postcode',
                'required' => false,
            ])
            
            ->add('city', TextType::class, [
                'label' => 'label.city',
                'required' => false,
            ]);

        });
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Center::class,
        ]);
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\FormBuilderInterface;

use Symfony\Component\OptionsResolver\OptionsResolver;

use Symfony\Component\Security\Core\Security;

use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;

/**
 * Defines the form used to edit an user.
 *
 * @author Romain Monteil <monteil.romain@gmail.com>
 */
class UserType extends AbstractType
{

    private $isAdmin;
    private $isOwner;
    private $isSuper;
    
    public function __construct(Security $security){

        $this->isAdmin = false;        
        $this->isOwner = false;
        $this->isSuper = false;

        $this->requestingUserId  = $security->getUser()->getId();

        // var_dump($this->requestingUserId);
       
        if (in_array('ROLE_ADMIN', $security->getUser()->getRoles()))
        {
            $this->isAdmin = true;
        }

        if (in_array('ROLE_SUPER_ADMIN', $security->getUser()->getRoles())) {
            $this->isAdmin = true;
            $this->isSuper = true;
        }

        if($security->getUser()->getCenterUser()){

        //    var_dump($security->getUser()->getCenterUser());

            $this->isOwner = true;
        }

        

    }        


    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {

        $builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) {

            $user = $event->getData();
            $form = $event->getForm();

            if($this->isAdmin){

                $form->add('email', EmailType::class, [
                    'label' => 'label.email'
                ]);

                $form->add('medic', CheckboxType::class, [
                    'label' => 'label.medic_role',
                    'required' => false,
                ]);

            } else {

                $form->add('email', TextType::class, [
                    'label' => 'label.email',
                    'disabled' => true,
                ]);
    
            }

            if($user->getId() <> $this->requestingUserId){ 
                // no se puede auto-cambiar a disabled o auto-revocar poderes

                $form->add('enabled', CheckboxType::class, [
                    'label' => 'label.enabled',
                    'required' => false,
                ]);

                if($this->isSuper || $this->isOwner){
                
                    $form->add('admin', CheckboxType::class, [
                        'label' => 'title.center_cpanel',
                        'required' => false,
                    ]);

                    if($this->isSuper){

                        $form->add('center_user', CheckboxType::class, [
                            'label' => 'title.center_owner',
                            'required' => false,
                        ]);
                    }
                }
            }

            $form->add('firstname', TextType::class, [
                'label' => 'label.firstname',
            ])
            ->add('lastname', TextType::class, [
                'label' => 'label.lastname',
            ])
            ->add('tel', TelType::class, [
                'label' => 'label.tel',
                'required' => false,
            ]);
            
        });   
  
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

templates/center/user/edit-medic.html.twig
{% extends 'base93.html.twig' %}

{% block main %}


<div class="card border-success mb-3">
        <h5><div class="card-header">{{ user.firstname }} {{ user.lastname }} <i class="fa fa-user-md"></i> {{user.email}} | {{user.tel}}</div></h5>

    <div class="card-body">

        <h5 class="card-title text-primary"> </h5>


        {{ form_start(form) }}

            <div class="form-row">

                <div class="form-group col-md-1">
                    {{ form_row(form.title) }}
                </div>

                <div class="form-group col-md-4">
                    {{ form_row(form.speciality) }}
                </div>

                <div class="form-group col-md-1"></div>

                <div class="form-group col-md-2 text-right"><i class="fa fa-home"></i></div>

                <div class="form-group col-md-3">
                     {{ form_row(form.internal) }}
                </div>

                <div class="form-group col-md-1">
                    {{ form_row(form.cod) }}
                </div>

            </div>

            <div class="form-row">

                <div class="form-group col-md-3">
                    {{ form_row(form.reg_code1) }}
                </div>
                <div class="form-group col-md-3">
                    {{ form_row(form.reg_code2) }}
                </div>
                <div class="form-group col-md-3">
                        {{ form_row(form.tax_code) }}
                </div>
            
            </div>

            <div class="form-row text-align-justify">

                <div class="form-group col">
                    <button type="submit" class="btn btn-primary">
                        <i class="fa fa-save" aria-hidden="true"></i> {{ 'action.save'|trans }}
                    </button>
                </div>

                <div class="form-group col text-right">
                    <a href="{{ path('medics_index', {slug:app.user.center.slug}) }}" class="btn btn btn-success">
                        <i class="fa fa-undo-alt"></i> {{ 'label.cancel'|trans }}
                    </a>
                </div>                

            </div>
    
        {{ form_end(form) }}

    </div>

</div>

{% endblock %}

{% block sidebar  %}
{% endblock %}

templates/center/user/index-medic.html.twig
{% extends 'base93.html.twig' %}

{% block main %}


<div class="body">

    <div class="row justify-content-between">

        <div class="column">
            <h4>
                <a href="{{ path('center_cpanel', {slug:center.slug}) }}">
                    <i class="fa fa-arrow-left" aria-hidden="true"></i> {{ center.name }}</a>
                | <i class="fa fa-user-md"></i> {{ 'label.medic.users'|trans }}
            </h4>
        </div>        

        <div class="column">
        </div>        

    </div>

</div>

{% if medics|length %}


    <table class="table table-responsive">
        <thead>
            <tr>
                <th></th>
                <th>{{'label.medic.title'|trans}}</th>
                <th>{{'label.firstname'|trans}}</th>
                <th>{{'label.lastname'|trans}}</th>
                <th class="text-center"><i class="fa fa-user-md"></i></th>
                
                <th>{{'label.medic.spec'|trans}}</th>
                <th></th>
                <th>{{'title.access'|trans}}</th>
                
                <th>{{'label.enabled'|trans}}</th>
                
            </tr>
            </thead>
        <tbody>
            {% for medic in medics %}
            <tr>
                <td>
                    <a href="{{ path('edit_user_medic',{slug:app.user.center.slug, id:medic.id}) }}" class="btn btn-sm btn-outline-success">
                        <i class="fa fa-edit" aria-hidden="true"></i> 
                    </a>
                </td>
                <td>{{ medic.title }}</td>
                <td>{{ medic.firstname }}</td>
                <td>{{ medic.lastname }} </td>
                <td>{{ medic.cod }}</td>
                
                <td>{{ medic.speciality }}</td>
                <td>
                    {% if medic.internal %}
                        <i class="fa fa-home"></i>
                    {% endif %}      
                </td>
                <td>{{ medic.email }} </td>
                
                <td class="text-center">

                    {% if medic.enabled %}
                            <i class="fa fa-toggle-on text-success"></i>
                    {% else %}  
                            <i class="fa fa-toggle-off text-danger"></i>
                    {% endif %} 
    
                </td>
                
            </tr>
            {% endfor %}
        </tbody>
    </table>

{% endif %}


{% endblock %}

templates/center/user/index.html.twig
{% extends 'base93.html.twig' %}

{% block main %}

    <nav aria-label="breadcrumb">

        <ol class="breadcrumb">

            

            {% if is_granted('ROLE_SUPER_ADMIN') %} 

                <li class="breadcrumb-item"><a href="{{ path('super_cpanel') }}">{{ 'title.super_cpanel'|trans }}</a></li>
                <li class="breadcrumb-item"><a href="{{ path('centers_index') }}">{{ 'title.centers_list'|trans }}</a></li>

            {% else %}

                {% if is_granted('ROLE_ADMIN') %} 
                    <li class="breadcrumb-item"><a href="{{ path('center_cpanel', {slug: center.slug}) }}">{{ 'title.center_cpanel'|trans }}</a></li>
                    <li class="breadcrumb-item enabled aria-current=page">{{ center.name }}</li>
                {% endif %}

            {% endif %}

        </ol>

    </nav>

    

    <div class="row">

        <div class="col-6">
            <h4><span class="text-info">{{ center.name }}</span> - <i class="fa fa-list-alt"></i> {{ 'title.users_list'|trans }}</h4>
        </div>        

        <div class="col-6">
            <div class="text-right">
                <a href="{{ path('user_new', {slug:slug}) }}" class="btn btn-primary">
                    <i class="fa fa-edit" aria-hidden="true"></i> {{ 'action.new'|trans }}
                </a>
            </div>
        </div>        

    </div>


    {% if users|length %}

         <table class="table table-striped table-hover table-responsive">

            <thead>
                <tr>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th>{{ 'label.name'|trans }}</th>
                    <th>{{ 'label.email'|trans }}</th>
                    <th>Tel</th>
                    <th>{{ 'title.patients'|trans }}</th>
                    <th class="text-center">{{'label.enabled'|trans}}</th>
                    
                </tr>
            </thead>

            <tbody>

            {% for user in users %}

                <tr>
                    <td> 
                    {% if not is_granted('IS_IMPERSONATOR') %}
                        <a href="{{ path('user_cpanel', {slug:app.user.center.slug, _switch_user:user.email} ) }}">
                            <i class="fa fa-user-circle text-danger"></i>
                        </a>
                    {% endif %}
                    </td>
                    <td class="text-center">

                        {# solo podemos editar el registro de ese usuario si
                        El demandante es el super
                        o
                        es el registro del mismo usuario
                        o
                        el demandante es el propietario del sistema
                        o
                        el registro es no es un administrador ni un super 
                        #}

                        {% if       is_granted('ROLE_SUPER_ADMIN')      
                                    or app.user.id == user.id
                                    or app.user.centerUser == app.user.center.id
                                    or (not('ROLE_ADMIN' in user.roles) and not('ROLE_SUPER_ADMIN' in user.roles))
                        %}

                            <div class="item-actions">
                                <a href="{{ path('user_edit', {slug:user.center.slug, id: user.id}) }}" class="btn btn-sm btn-outline-primary">
                                    <i class="fa fa-edit" aria-hidden="true"></i>
                                </a>
                            </div>
                        
                        {% else %}
                        {% endif %}

                    </td>
                    <td>
                        {% if user.centerUser == user.id %}
                        <i class="fa fa-key text-warning"></i>
                        {% endif %}

                        {% if 'ROLE_ADMIN' in user.roles or 'ROLE_SUPER_ADMIN' in user.roles %}
                        <i class="fa fa-key text-info"></i>
                        {% endif %}
                    </td>

                    <td>{% if user.medic %}<i class="fa fa-user-md"></i>{% endif %}</td>
                    <td>
                        {{ user.firstname }} {{ user.lastname }}
                    </td>
                    <td>
                        {{ user.email }} 
                    </td>    
                    <td>
                        {{ user.tel }}
                    </td>

                    <td class="text-center">
                        {#  user.patients|length #}
                    </td>

                    <td class="text-center">
                        {% if user.enabled %}
                            <i class="fa fa-toggle-on text-success"></i>
                        {% else %}  
                            <i class="fa fa-toggle-off text-danger"></i>
                        {% endif %}  
                    </td>



                </tr>
            {% endfor %}


            </tbody>

        </table>


    {% endif %}



    
{% endblock %}


{% block sidebar %}

    {% if is_granted('IS_IMPERSONATOR') %}
        <a href="{{ path('users_index', {slug:center.slug,'_switch_user': '_exit'}) }}" class="btn btn-block btn-danger">
            <i class="fa fa-user-shield"></i> Exit impersonation
        </a>
    {% endif %}

    <div class="card">

        <div class="card-header">
            <h4>{{ 'company.data'|trans }}</h4>
        </div>

        <div class="card-body">

            <h5 class="card-title text-info">{{ center.name }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{{ center.contactPerson }}</h6>

            <p class="card-text"></p>
            <p class="card-text">
                {{ center.address }}<br>
                {{ center.postcode }} {{ center.city }}
            </p>
            <p class="card-text"></p>
            <p class="card-text">
                {{ center.tel }}<br>
                {{ center.email }}
            </p>

            <p class="card-text"></p>

            <a href="{{ path('center_edit', {slug: center.slug}) }}" class="btn btn-block btn btn-primary">
                <i class="fa fa-edit" aria-hidden="true"></i> {{ 'action.edit'|trans }}
            </a>        

        </div>

    </div>
   
{% endblock %}

templates/center/user/new.html.twig
{% extends 'base93.html.twig' %}

{% block body_id 'user_new' %}

{% block main %}

{# dump(user) #}

    <h4><i class="fa fa-user"></i> {{ 'title.new_user'|trans }}</h4>

    {{ form_start(form) }}

        <div class="form-row">
            <div class="form-group col-md-4">
                {{ form_row(form.firstname) }}
            </div>        
            <div class="form-group col-md-4">
                {{ form_row(form.lastname) }}
            </div>
        </div>
       
        <div class="form-row">
            <div class="form-group col-md-8">
                {{ form_row(form.email) }}
            </div>
            <div class="form-group col-md-4">
                {{ form_row(form.tel) }}
            </div>     
        </div>

        <div class="form-row">
            <div class="form-group col-md-4">
                {{ form_row(form.password) }}
            </div>        
        </div>

        <div class="form-row">

            <div class="form-group col-sm-6"></div>

            <div class="form-group col-sm-3">
                <a href="{{ path('users_index', {slug: user.center.slug}) }}" class="btn btn-block btn-success">
                    <i class="fa fa-arrow-left" aria-hidden="true"></i> {{ 'title.users_list'|trans }}
                </a>        
            </div>
                        
            <div class="form-group col-sm-3">
                <button type="submit" class="btn btn-block btn-primary">
                    <i class="fa fa-save" aria-hidden="true"></i> {{ 'action.save'|trans }}
                </button>
            </div>
            
        </div>

    {{ form_end(form) }}

    <br>

{% endblock %}


{% block sidebar %}

    {{ parent() }}
    {# show_source_code(_self) #}

{% endblock %}