src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=127)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=127, nullable=true)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=63, nullable=true)
     */
    private $tel;

    /**
     * @ORM\Column(type="boolean")
     */
    private $enabled;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToOne(targetEntity=Center::class, inversedBy="users", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $center;

    /**
     * @ORM\OneToMany(targetEntity=Patient::class, mappedBy="user")
     */
    private $patients;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $medic;

    /**
     * @ORM\Column(type="string", length=3, nullable=true)
     */
    private $cod;

    /**
     * @ORM\Column(type="string", length=15, nullable=true)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=127, nullable=true)
     */
    private $speciality;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $internal;

    /**
     * @ORM\Column(type="string", length=63, nullable=true)
     */
    private $tax_code;

    /**
     * @ORM\Column(type="string", length=63, nullable=true)
     */
    private $reg_code1;

    /**
     * @ORM\Column(type="string", length=63, nullable=true)
     */
    private $reg_code2;

    /**
     * @ORM\OneToMany(targetEntity=DocUser::class, mappedBy="user")
     */
    private $docs;

    /**
     * @ORM\OneToMany(targetEntity=Opera::class, mappedBy="user", orphanRemoval=true)
     */
    private $operas;

    /**
     * @ORM\OneToMany(targetEntity=Consult::class, mappedBy="user")
     */
    private $consults;

    /**
     * @ORM\OneToMany(targetEntity=Medicat::class, mappedBy="user")
     */
    private $medicats;

    /**
     * @ORM\OneToMany(targetEntity=Historia::class, mappedBy="user")
     */
    private $historias;

    /**
     * @ORM\OneToMany(targetEntity=UserLog::class, mappedBy="user")
     */
    private $userLogs;

    /**
     * @ORM\OneToMany(targetEntity=Report::class, mappedBy="user")
     */
    private $reports;


    





    
    public function __construct()
    {
        $this->patients = new ArrayCollection();
        $this->docs = new ArrayCollection();
        $this->operas = new ArrayCollection();
        $this->consults = new ArrayCollection();
        $this->medicats = new ArrayCollection();
        $this->historias = new ArrayCollection();
        $this->userLogs = new ArrayCollection();
        $this->reports = new ArrayCollection();
    }

    public function getPatientsNo() 
    {
        $patientsNo = $this->getPatients()->count();
        return $patientsNo;
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(?string $tel): self
    {
        $this->tel = $tel;

        return $this;
    }

    public function getEnabled(): ?bool
    {
        return $this->enabled;
    }

    public function setEnabled(bool $enabled): self
    {
        $this->enabled = $enabled;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getCenter(): ?Center
    {
        return $this->center;
    }

    public function setCenter(?Center $center): self
    {
        $this->center = $center;

        return $this;
    }










    public function getAdmin(){

        if (in_array('ROLE_ADMIN', $this->getRoles()) 
                || in_array('ROLE_SUPER_ADMIN', $this->getRoles())) {
            return true;
        }
    }
    
    public function getCenterUser(){
        if ($this->getCenter()) {
            return ($this === $this->getCenter()->getUser());
        } else {
            return false;
        }
    }

    public function setAdmin(bool $admin)
    {
        if($admin || $this->getCenterUser()){
            if (!in_array('ROLE_SUPER_ADMIN', $this->getRoles())) {
                $this->setRoles(['ROLE_ADMIN']);
            }
            $this->setEnabled(true);
        } else {
            $this->setRoles([]);            
        }
        
        return $this;
    }

    public function setCenterUser(bool $update)
    {
        if($update) {
            $this->getCenter()->setUser($this);
            // Hacemos administrador a este usuario
            $this->setAdmin(true);
        } else {
            $this->getCenter()->setUser(null);
        }

        return $this;
        
    }

    /**
     * @return Collection|Patient[]
     */
    public function getPatients(): Collection
    {
        return $this->patients;
    }

    public function addPatient(Patient $patient): self
    {
        if (!$this->patients->contains($patient)) {
            $this->patients[] = $patient;
            $patient->setUser($this);
        }

        return $this;
    }

    public function removePatient(Patient $patient): self
    {
        if ($this->patients->contains($patient)) {
            $this->patients->removeElement($patient);
            // set the owning side to null (unless already changed)
            if ($patient->getUser() === $this) {
                $patient->setUser(null);
            }
        }

        return $this;
    }

    public function getMedic(): ?bool
    {
        return $this->medic;
    }

    public function setMedic(?bool $medic): self
    {
        $this->medic = $medic;

        return $this;
    }

    public function getCod(): ?string
    {
        return $this->cod;
    }

    public function setCod(?string $cod): self
    {
        $this->cod = $cod;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSpeciality(): ?string
    {
        return $this->speciality;
    }

    public function setSpeciality(?string $speciality): self
    {
        $this->speciality = $speciality;

        return $this;
    }

    public function getInternal(): ?bool
    {
        return $this->internal;
    }

    public function setInternal(?bool $internal): self
    {
        $this->internal = $internal;

        return $this;
    }

    public function getTaxCode(): ?string
    {
        return $this->tax_code;
    }

    public function setTaxCode(?string $tax_code): self
    {
        $this->tax_code = $tax_code;

        return $this;
    }

    public function getRegCode1(): ?string
    {
        return $this->reg_code1;
    }

    public function setRegCode1(?string $reg_code1): self
    {
        $this->reg_code1 = $reg_code1;

        return $this;
    }

    public function getRegCode2(): ?string
    {
        return $this->reg_code2;
    }

    public function setRegCode2(?string $reg_code2): self
    {
        $this->reg_code2 = $reg_code2;

        return $this;
    }

    /**

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\FormBuilderInterface;

use Symfony\Component\OptionsResolver\OptionsResolver;

use Symfony\Component\Security\Core\Security;

use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;

/**
 * Defines the form used to edit an user.
 *
 * @author Romain Monteil <monteil.romain@gmail.com>
 */
class UserType extends AbstractType
{

    private $isAdmin;
    private $isOwner;
    private $isSuper;
    
    public function __construct(Security $security){

        $this->isAdmin = false;        
        $this->isOwner = false;
        $this->isSuper = false;

        $this->requestingUserId  = $security->getUser()->getId();

        // var_dump($this->requestingUserId);
       
        if (in_array('ROLE_ADMIN', $security->getUser()->getRoles()))
        {
            $this->isAdmin = true;
        }

        if (in_array('ROLE_SUPER_ADMIN', $security->getUser()->getRoles())) {
            $this->isAdmin = true;
            $this->isSuper = true;
        }

        if($security->getUser()->getCenterUser()){

        //    var_dump($security->getUser()->getCenterUser());

            $this->isOwner = true;
        }

        

    }        


    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {

        $builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) {

            $user = $event->getData();
            $form = $event->getForm();

            if($this->isAdmin){

                $form->add('email', EmailType::class, [
                    'label' => 'label.email'
                ]);

                $form->add('medic', CheckboxType::class, [
                    'label' => 'label.medic_role',
                    'required' => false,
                ]);

            } else {

                $form->add('email', TextType::class, [
                    'label' => 'label.email',
                    'disabled' => true,
                ]);
    
            }

            if($user->getId() <> $this->requestingUserId){ 
                // no se puede auto-cambiar a disabled o auto-revocar poderes

                $form->add('enabled', CheckboxType::class, [
                    'label' => 'label.enabled',
                    'required' => false,
                ]);

                if($this->isSuper || $this->isOwner){
                
                    $form->add('admin', CheckboxType::class, [
                        'label' => 'title.center_cpanel',
                        'required' => false,
                    ]);

                    if($this->isSuper){

                        $form->add('center_user', CheckboxType::class, [
                            'label' => 'title.center_owner',
                            'required' => false,
                        ]);
                    }
                }
            }

            $form->add('firstname', TextType::class, [
                'label' => 'label.firstname',
            ])
            ->add('lastname', TextType::class, [
                'label' => 'label.lastname',
            ])
            ->add('tel', TelType::class, [
                'label' => 'label.tel',
                'required' => false,
            ]);
            
        });   
  
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

templates/user/change_password.html.twig
{% extends 'base93.html.twig' %}

{% block body_id 'user_password' %}

{% block main %}

    <h4>{{ 'action.change_password'|trans }}</h4>

    {% if app.user.id == user.id %}
        <div class="alert alert-info" role="alert">
            {{ 'info.change_password'|trans }}
        </div>
    {% else %}              
    {% endif %}        

  

    {{ form_start(form) }}
        
            {{ form_widget(form) }}
        
        
            <div class="form-group row">
                <div class="col-sm-5">
                    <button type="submit" class="btn btn-block btn-primary">
                        <i class="fa fa-save" aria-hidden="true"></i> {{ 'action.save'|trans }}
                    </button>
                </div>
                <div class="col-sm-2">
                </div>
                <div class="col-sm-5">
                    <a href="{{ path('profile_edit') }}" class="btn btn-block btn-success">
                        <i class="fa fa-arrow-left" aria-hidden="true"></i> {{ 'label.cancel'|trans }}
                    </a>                
                </div>
            </div>

    {{ form_end(form) }}



    <br/>


{% endblock %}

{% block sidebar %}

    <div class="container">

        <div class="row">
        </div>

        {{ parent() }}
        {# show_source_code(_self) #}

    </div>

    
{% endblock %}

templates/user/cpanel.html.twig
{% extends 'base.html.twig' %}

{% block title %}Panel{% endblock %}

{% block header %}
    {{ include('_header.html.twig') }}
{% endblock %}

{% block body %}

    <div class="row">

        <div class="col-sm-3">
            <div class="card">
                <div class="card-header"> 
                    <h5><i class="fa fa-users"></i> {{ 'title.patients'|trans|upper }}</h5>
                </div>
                <div class="card-body">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"><i class="fa fa-clipboard"></i> <a href="{{ path('patient_new',{slug:app.user.center.slug} ) }}">{{ 'action.new'|trans }} {{ 'label.patient'|trans }}</a></li>
                        <li class="list-group-item"><i class="fa fa-list-alt"></i> <a href="{{ path('patient_index', {slug:center.slug}) }}">{{ 'label.last.records'|trans }}</a></li>
                        <li class="list-group-item"><i class="fa fa-search"></i> <a href="{{ path('patient_search', {slug:center.slug} ) }}">{{ 'label.search'|trans }}</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="col-sm-3">
            <div class="card">
                <div class="card-header"> 
                    <h5><i class="fa fa-calendar-check-o"></i> Agendas</h5>
                </div>
                <div class="card-body">
                    <ul class="list-group list-group-flush">
                        {% for agenda in agendas %}
                            <li class="list-group-item">
                                <form method="post" action="https://www.supersaas.com/api/users" target="_blank">
                                    <input type="hidden" name="account" value="{{ ac_name }}"/>
                                    <input type="hidden" name="id" value="{{ user.id }}fk"/> <!-- The user has ID 1234 on your server's database -->
                                    <input type="hidden" name="user[name]" value="{{ user.email }}"/>
                                    <input type="hidden" name="user[phone]" value=""/>
                                    <!-- you can add and remove fields on the "Access Control" screen -->
                                    <input type="hidden" name="checksum" value="{{ checksum }}"/>
                                    <input type="hidden" name="after" value="{{ agenda.name }}"/>
                                    <input type="submit" class="btn btn-block btn-secondary" value="{{ agenda.name }}"/>
                                </form>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>  

        <div class="col-sm-3">

            <div class="card">
                <div class="card-header"> 
                    <h5><i class="fa fa-folder-open-o"></i> {{'label.docs'|trans}}</h5>
                </div>
                <div class="card-body">
                    <ul class="list-group list-group-flush">
                    {% for group in groups %}
                        <li class="list-group-item"><i class="fa fa-file-o"></i> <a href="{{ path('docs_index', {slug:center.slug, id:group.id} ) }}">{{ group.name }}</a></li>
                    {% endfor %}
                    </ul>
                </div>
            </div>

            <br>

            <div class="card">
                <div class="card-header"> 
                    <h5><i class="fa fa-folder-open"></i> {{'label.reports'|trans}}</h5>
                </div>
                <div class="card-body">
                    <ul class="list-group list-group-flush">
                    {% for group in groups %}
                        <li class="list-group-item"><i class="fa fa-file-o"></i> <a href="{{ path('docs_index', {slug:center.slug, id:group.id} ) }}">{{ group.name }}</a></li>
                    {% endfor %}
                    </ul>
                </div>
            </div>



        </div>

        <div class="col-sm-3">
            <div class="card">
                <div class="card-header">
                    <h5><i class="fa fa-sticky-note-o"></i> {{ 'label.stats'|trans|upper }}</h5>
                </div>
                <div class="card-body">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"><i class="fa fa-clipboard"></i> <a href="{{ path('stats_treatments',{slug:app.user.center.slug} ) }}">{{ 'label.treatments'|trans }}</a></li>

                    </ul>
                </div>
            </div>
            
        </div>



    </div>
    
{% endblock %}

templates/user/edit.html.twig
{% extends 'base93.html.twig' %}

{% block body_id 'user_edit' %}

{% block main %}

    {% if app.user.id != user.id and is_granted('ROLE_ADMIN') or is_granted('ROLE_SUPER_ADMIN') %} 

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">

                {% if is_granted('ROLE_SUPER_ADMIN') %} 
                    <li class="breadcrumb-item"><a href="{{ path('super_cpanel') }}">{{ 'title.super_cpanel'|trans }}</a></li>
                    <li class="breadcrumb-item"><a href="{{ path('centers_index') }}">{{ 'title.centers_list'|trans }}</a></li>
                {% endif %}

                {% if is_granted('ROLE_ADMIN') and not is_granted('ROLE_SUPER_ADMIN') %} 
                        <li class="breadcrumb-item"><a href="{{ path('center_cpanel', {slug:app.user.center.slug}) }}">{{ 'title.center_cpanel'|trans }}</a></li>
                {% endif %}

                <li class="breadcrumb-item aria-current=page"><a href="{{ path('users_index', {slug:app.user.center.slug}) }}">{{ user.center.name }}</a></li>
                
            </ol>
        </nav>

    {% endif %}

    <div class="row justify-content-between">

        <div class="col">
            <h4>{{ 'title.edit_user'|trans }} <i class="fa fa-user"></i> <span class="text-success">{{ user.email }}</span></h4>
        </div>        
        <div class="col text-right">
            {% if is_granted('ROLE_ADMIN') or is_granted('ROLE_SUPER_ADMIN') %}
            <h5>{{ 'label.recorded'|trans }}: {{user.createdAt|date("d/m/Y") }} </h5>
                {% if 'ROLE_ADMIN' in user.roles %}
                    {{ 'title.center_cpanel'|trans }} <i class="fa fa-key text-info"></i> 
                {% endif %}        
                {% if user.centerUser == user.id %}
                    {{ 'title.center_owner'|trans }} <i class="fa fa-key text-warning"></i> 
                {% endif %}        
            {% endif %}        
        </div>     
        
    </div>    

    {{ form_start(form) }}


        <div class="form-row">

            {% if app.user.id != user.id %} 

                <div class="form-group col-auto">
                    {{ form_row(form.enabled) }}
                </div> 
                {% if app.user.centerUser == app.user.center.id or is_granted('ROLE_SUPER_ADMIN') %}        
                <div class="form-group col-auto">
                    {{ form_row(form.admin) }}
                </div>
                {% endif %}
                {% if is_granted('ROLE_SUPER_ADMIN') %}        
                <div class="form-group col-auto">
                    {{ form_row(form.center_user) }}
                </div>
                {% endif %}

            {% endif %}

            {% if is_granted('ROLE_ADMIN') %}        

                <div class="form-group col-auto text-right"> <i class="fa fa-user-md"></i></div>
                <div class="form-group col-auto">
                    {{ form_row(form.medic) }}
                </div>
            {% endif %}

        </div> 

        <div class="form-row">
            <div class="form-group col-md-8">
                {{ form_row(form.email) }}
            </div>
            <div class="form-group col-md-4">
                {{ form_row(form.tel) }}
            </div> 
        </div>
    
        <div class="form-row">
            <div class="form-group col-md-4">
                {{ form_row(form.firstname) }}
            </div>        
            <div class="form-group col-md-4">
                {{ form_row(form.lastname) }}
            </div>
        </div>

        <div class="form-row justify-content-between">  

            <div class="form-group col-sm-3">
                {% if app.user != user or is_granted('ROLE_SUPER_ADMIN') %}
                <div class="form-group text-right">
                    <a href="{{ path('users_index', {slug:app.user.center.slug}) }}" class="btn btn-block btn-success">
                        <i class="fa fa-arrow-left" aria-hidden="true"></i> {{ 'title.users_list'|trans }}
                    </a>
                </div>
                {% else %} 
                    <a href="{{ path('user_cpanel', {slug:app.user.center.slug} ) }}" class="btn btn-block btn-success">
                        <i class="fa fa-arrow-left" aria-hidden="true"></i> {{ 'label.cancel'|trans }}
                    </a>                
                {% endif %} 
            </div>            

            <div class="form-group col-sm-3">
                <button type="submit" class="btn btn-block btn-primary">
                    <i class="fa fa-save" aria-hidden="true"></i> {{ 'action.save'|trans }}
                </button>
            </div>

        </div>


    {{ form_end(form) }}

{% endblock %}


{% block sidebar %}

    {% if app.user.id == user.id %}
    {# Cambiamos SOLO la contraseña propia #} 

        <div class="row">

            <div class="col-sm">

                <a href="{{ path('user_change_password') }}" class="btn btn-lg btn-block btn-danger">
                    <i class="fa fa-lock" aria-hidden="true"></i> {{ 'action.change_password'|trans }}
                </a>

            </div>

        </div>

        <br>

    {% endif %}

    {% if is_granted('ROLE_ADMIN') or is_granted('ROLE_SUPER_ADMIN') %}
    
    <div class="row">

        <div class="col-sm">
                
            <div class="card">

                <div class="card-header">
                    <h5>{{ 'security.title'|trans }}</h5>
                </div>

                <div class="card-body">
            
                    <h6 class="card-text text-primary">
                        <i class="fa fa-key text-warning"></i> {{ 'title.center_owner'|trans }}<br>{{ 'security.owner_1'|trans }}
                    </h6>

                    <br>

                    <h6 class="card-text text-primary">
                        <i class="fa fa-key text-info"></i> {{ 'title.center_cpanel'|trans }}<br>{{ 'security.admin_1'|trans }}
                    </h6>
                    <br>

                </div>

            </div>

        </div>

    </div>
                
    {% endif %}
    
{% endblock %}